### PR TITLE
Different fixes

### PR DESCRIPTION
**Pull request by bjoernwe**
- Updated index files for the new interview structure
- Updates for outdated links
- Some formatting issues and typos fixed

### CODE REVIEW

**Comment by joncamfield** [comment]
@bjoernwe Thanks again for all the tweaks and fixes. I've also updated the password survey location and fixed that in your index files.

Would it be possible to pull out the playlist work into a separate pull request to review it without slowing down the merge of the pure fixes?

**Comment by bjoernwe** [comment]
Yes. Actually, the playlist changes where not supposed to be in that branch/pull request. They somehow managed to chisel into it. I'll sort this out.

**Comment by bjoernwe** [comment]
Okay, commits regarding the playlist work are removed.

**Comment by joncamfield** [comment]
Thanks for all the fixes!

**Pull request merged**
