### PR TITLE
Adding Advanced threat Method and exercise

### PR DESCRIPTION
**Pull request by dlshad**
In this method, we are discussing the issue of advanced threat, mostly finding a malware or a suspicious activities on a machine and how to deal with it.

### CODE REVIEW

**Comment by dlshad** [comment]
Awesome! thanks @cguerrave , I just uploaded the exercise part.

**Comment by joncamfield** [comment]
This is a great start! I made some edits to expand the scope of the method and add it in to the main index, plus a few formatting tweaks described in the commit messages.

I think the exercise should probably be separated into two:

1) threat hunting -- to responsibly address a suspicion of malware/compromise without specific evidence,  digging in and pointing to the concepts at http://www.threathunting.net/

2) Malware analysis -- this is basically what the advanced threat exercise is already -- to focus on on-site analysis and triage when there is an identified email/file/process.

We should work through some of the operational security questions here and revisit the existing incident response content to update it accordingly.  

@dlshad Can you review my changes, work on first focusing the advanced_threat exercise to the more specific analysis case, and begin a separate exercise for the detection/hunting case?  Also, can you look in to the commits in the adids folder and see what happened there? Were they old, un-merged curricula edits hiding in the dev branch?

**Comment by dlshad** [comment]
@joncamfield Done!

**Comment by joncamfield** [comment]
Merged! As we prep for the possible February event, let's ask for suggestions of what else needs to be added , alternative approaches, etc. for this section.

**Pull request merged**
