### PR TITLE
Add/method icons

### PR DESCRIPTION
**Pull request by LanesGood**
Adds method icon to method pages:

### CODE REVIEW

**Review by vgeorge — APPROVED** [review]
@LanesGood The implementation looks good. Not all methods have logos, but I guess they can be added later.

**Review by joncamfield — CHANGES_REQUESTED** [review]
This looks good, can we also add the icons to the listing of the methods (or does that happen automagically by pulling summaries from this layout?)

**Comment by LanesGood** [comment]
@joncamfield Good suggestion - I've added the icon to the cards as seen in the screenshot below:
image

**Comment by joncamfield** [comment]
Thanks! merging.

**Pull request merged**
