### PR TITLE
Remote assessment

### PR DESCRIPTION
**Pull request by florianap**

### CODE REVIEW

**Comment by florianap** [comment]
Added  remote assessment exercise for network mapping and device assessment

**Comment by joncamfield** [comment]
A few (ok, a lot) stylistic requests, because I gave bad guidance on file templates.  I will work to adapt the network mapping pieces into the exercise format.  Please note that the actual content here is fantastic, many thanks for the hard work and testing your team did to put this together.

One content request:

* In operational_security.md , please consider adding points on having a secure communication channel via a different device than the one being rebooted into a live environment for support/debugging/making sure they don't press "install" and format their machine, and the importance of transferring the ssh commands over secure channels, acquiring the image over TLS (and checking signatures?), and using an updated, secured, or updated and ephemeral server for the middle connection.

Formatting/file requests:

* Add an index.md file, change the "name" of this activity (from "Activity Title"), but otherwise a copy of this: https://github.com/SAFETAG/SAFETAG/blob/master/en/templates/folders/activity/index.md
* Activity title is h4 (####) and the sub-titles are h5, so please constrain in-document section titles to h6 and bold (I know, bold isn't correct for semantic header usage :cry: )
* Remove the activities.md file - I will link this activity in to the master guide index once merged.
* Rename approaches.md to approach.md
* Remove guiding_questions.md - this is used at the methodology level, not the activity level (mea culpa!)
* Update materials_needed.md needed to h6 headers
* We don't use output.md in the generated content any more, consider moving the information there to summary.md
* We also don't use preparation.md, consider moving that to materials_needed.md?
* Update walkthrough to h6 formatting. Once merged, I may also format it a bit further or edit for clarity, but amazing work.

**Comment by joncamfield** [comment]
Thank you for not only a great option to adapt this work remotely, but for such a quick turn-around on comments!

**Comment by joncamfield** [comment]
I've made some last tweaks to get the title in and the file linked in to the broader SAFETAG index files.

**Pull request merged**
