### PR TITLE
Install osx

### PR DESCRIPTION
**Pull request by mishari**
I added some instructions as well as changed the makefile so that it works in OSX.

### CODE REVIEW

**Comment by elationfoundation** [comment]
Thanks!  Does the  "--parents" flag for mkdir not work on OSX?

**Comment by mishari** [comment]
Affirmative.

**Comment by elationfoundation** [comment]
Well, that is so frustrating. Thanks for this. I will have access to a OSX machine next week to test this out on and merge it in.

**Comment by joncamfield** [comment]
Closing; this portion of SAFETAG is now managed in a separate repository at https://github.com/OpenInternet/Documentation-Builder/ ; and we are investigating a metalsmith-driven build approach moving forward.

**Pull request closed without merging**
